openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/AAFC/test/1.0.0
info:
  description: PCR Primer schema corresponding to a sequence pcrprimer
  version: "1.0.0"
  title: PCR Primer schema
  contact:
    email: you@your-compay.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /v1/pcr-primer:
    get:
      tags:
        - PCR Primer
      summary: get pcr-primer
      operationId: getPcrPrimers
      description: By passing in query string, user ca get available pcrPrimers authorised
      parameters:
        - in: query
          name: filter[rsql]
          description: pass a optional search string for looking up the pcrPrimers
          schema:
            type: string
        - in: query
          name: sort
          description: optional sort string, can have sort order such as descending denoted by "-"
          schema:
            type: string
        - in: query
          name: page[offset]
          description: number of records to skip when paging
          schema:
            type: integer
            format: int32
        - in: query
          name: page[limit]
          description: maximum number of records to return when paging
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: pcrPrimers satifying the query restrictions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PcrPrimer'
        '400':
          description: bad input parameter
        '404':
          description: pcrPrimers not found
    post:
      tags:
        - PCR Primer
      summary: adds a pcr-primer
      operationId: addPcrPrimer
      description: Adds a pcr-primer
      responses:
        '201':
          description: pcr-primer created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: a pcr-primer already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPcrPrimer'
        description: pcr-primer to add
  /v1/pcr-primer/{Id}:
    get:
      tags:
        - PCR Primer
      summary: Find pcr-primer by ID
      description: Returns a single pcr-primer
      operationId: getPcrPrimerById
      parameters:
        - name: Id
          in: path
          description: ID of pcr-primer to return
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PcrPrimer'
        "400":
          description: Invalid ID supplied
        "404":
          description: pcr-primer not found
    patch:
      tags:
        - PCR Primer
      summary: update a pcr-primer
      operationId: updatePcrPrimer
      description: update a pcr-primer
      parameters:
        - name: Id
          in: path
          description: pcr-primer id to patch
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: pcr-primer updated
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PcrPrimer'
        description: pcr-primer to update
    delete:
      tags:
        - PCR Primer
      summary: delete a pcr-primer
      operationId: deletePcrPrimer
      description: delete a pcr-primer
      parameters:
        - name: Id
          in: path
          description: pcr-primer id to delete
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: pcr-primer marked as deleted
        '400':
          description: invalid ID supplied
        '404':
          description: pcr-primer not found

components:
  schemas:
    PcrPrimer:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
          properties:
            id:
              type: string
          allOf:
           - $ref: '#/components/schemas/CommonPcrPrimer'
           
    NewPcrPrimer:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          allOf:
           - $ref: '#/components/schemas/CommonPcrPrimer'
                      
    CommonPcrPrimer:
      type: object
      required:
        - type
        - attributes
      properties:
        type:
          enum: [pcr-primer]      
          description: The type of data being returned.
        attributes:
          description: Schema representing the PcrPrimer
          type: object
          required:
            - name
            - type
            - seq
            - lotNumber
          properties:
            createdBy:
              type: string      
              readOnly: true
              description: authenticated user who created the pcr-primer
            createdOn:              
              type: string
              format: date-time                            
              readOnly: true
              description: date and time when the pcr-primer was created in ISO format
              example: 1985-04-12T23:20:50.52Z
            group:
              type: string
              nullable: true
              description: The group in which the pcr-primer belongs to
            name:
              type: string
            type:
              enum:
                - PRIMER
                - MID
                - FUSION_PRIMER
                - ILLUMINA_INDEX
                - ITRU_PRIMER
              description: Primer types
            seq:
              type: string
              description: A short DNA sequence string
            lotNumber:
              type: integer
            version:
              type: integer
            direction:
              type: string 
              description: A primer direction such as forward or reverse
            tmCalculated:
              type: string 
            tmPe:
              type: integer
            position:
              type: string
            note:
              type: string
            lastModified:
              type: string
            application:
              type: string
            reference:
              type: string
            targetSpecies:
              type: string
            supplier:
              type: string
            dateOrdered:
              type: string
            purification:
              type: string
            designedBy:
              type: string
            stockConcentration:
              type: string
        relationships:
          type: object
          required: 
            - region
          properties:
            region:
              $ref: region.yml#/components/schemas/LinkedRegion











