openapi: 3.0.0
servers:
  - description: DINA - AAFC
    url: https://virtserver.dina-aafc.com/AAFC/1.0.0
info:
  description: SeqDB API Schema
  version: "1.0.0"
  title: SeqDB API Schema
  contact:
    email: dina-aafc@canada.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
   
paths:
  /v1/region:
    $ref: 'region.yml#/paths/~1v1~1region'
  /v1/region/{Id}:
    $ref: 'region.yml#/paths/~1v1~1region~1{Id}'  
  /v1/pcr-primer:
    $ref: 'pcrPrimer.yml#/paths/~1v1~1pcr-primer'    
  /v1/pcr-primer/{Id}:
    $ref: 'pcrPrimer.yml#/paths/~1v1~1pcr-primer~1{Id}'
  /v1/pcr-batch:
    $ref: 'pcrBatch.yml#/paths/~1v1~1pcr-batch'
  /v1/pcr-batch/{Id}:
    $ref: 'pcrBatch.yml#/paths/~1v1~1pcr-batch~1{Id}'
  /v1/seq-batch:
    $ref: 'seqBatch.yml#/paths/~1v1~1seq-batch'
  /v1/seq-batch/{Id}:
    $ref: 'seqBatch.yml#/paths/~1v1~1seq-batch~1{Id}'
  /v1/seq-reaction:
    $ref: 'seqReaction.yml#/paths/~1v1~1seq-reaction'
  /v1/seq-reaction/{Id}:
    $ref: 'seqReaction.yml#/paths/~1v1~1seq-reaction~1{Id}'
  /v1/sequencing-facility:
    $ref: 'sequencingFacility.yml#/paths/~1v1~1sequencing-facility'
  /v1/sequencing-facility/{Id}:
    $ref: 'sequencingFacility.yml#/paths/~1v1~1sequencing-facility~1{Id}'
  /v1/seq-submission:
    $ref: 'seqSubmission.yml#/paths/~1v1~1seq-submission'
  /v1/seq-submission/{Id}:
    $ref: 'seqSubmission.yml#/paths/~1v1~1seq-submission~1{Id}'
